### ISSUE TITLE
Change template structure

### ISSUE THREAD

**Issue by dpodvyaznikov** [gazprom-neft/ml_project_template#1]
I suggest to change current structure from this
```
.repo_name
├── ...
├── Library submodule
├── src
|    └── ...
└── ...
```
to this
```
.repo_name
├── ...
├── project_name
│   ├── __init__.py
│   ├── src
|        └── ...
|   └── Library submodule(s)
└── ...
```

This way we could get rid of `sys.path.append('..')` needed now for `.py` files in `src` that import stuff from submodules, and use `project_name` as a module.

**Comment by dpodvyaznikov** [comment]
Update after discussion:

```
.repo_name
├── ...
├── src
│   ├── __init__.py
│   ├── Library submodule(s)
|   └── ...
└── ...
```

@a-arefina , can you please implement this?

**Comment by a-arefina** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Поменять структуру проекта в шаблоне](https://trello.com/c/ljGxwOON/67-%D0%BF%D0%BE%D0%BC%D0%B5%D0%BD%D1%8F%D1%82%D1%8C-%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D1%83-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0-%D0%B2-%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%B5)
